// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lockout.sql

package usersdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getLockoutStatus = `-- name: GetLockoutStatus :one
SELECT failed_attempts, locked_until
FROM users
WHERE id = $1
`

type GetLockoutStatusRow struct {
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) GetLockoutStatus(ctx context.Context, id uuid.UUID) (GetLockoutStatusRow, error) {
	row := q.db.QueryRow(ctx, getLockoutStatus, id)
	var i GetLockoutStatusRow
	err := row.Scan(&i.FailedAttempts, &i.LockedUntil)
	return i, err
}

const incrementFailedAttempts = `-- name: IncrementFailedAttempts :one
UPDATE users
SET failed_attempts = failed_attempts + 1
WHERE id = $1
RETURNING failed_attempts
`

func (q *Queries) IncrementFailedAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementFailedAttempts, id)
	var failed_attempts int32
	err := row.Scan(&failed_attempts)
	return failed_attempts, err
}

const lockUser = `-- name: LockUser :exec
UPDATE users
SET locked_until = $2
WHERE id = $1
`

type LockUserParams struct {
	ID          uuid.UUID          `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) LockUser(ctx context.Context, arg LockUserParams) error {
	_, err := q.db.Exec(ctx, lockUser, arg.ID, arg.LockedUntil)
	return err
}

const resetLockout = `-- name: ResetLockout :exec
UPDATE users
SET failed_attempts = 0, locked_until = NULL
WHERE id = $1
`

func (q *Queries) ResetLockout(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetLockout, id)
	return err
}
